version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=hey
      - POSTGRES_PASSWORD=hey2022
    ports:
      - 5432:5432
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=my_db
      - POSTGRES_USER=hey
      - POSTGRES_PASSWORD=hey2022
    depends_on:
      - db